version: '3.7'

services:

  crwn-clothing:
    container_name: crwn-clothing
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true  